#!/bin/sh
export STEPLIB='CBC.SCCNCMP'
export _C89_SSYSLIB='CEE.SCEEMAC:SYS1.MACLIB:ASM.SASMMAC2'
export JAVA_HOME='/var/java17_31/J7.0'

c89 -c -W a,RENT,GOFF BLZTEST1.s
c89 -W l,AC=1,REUS=NONE,XPLINK -o testHFS BLZTEST1.o
